# Generated by Django 5.2.4 on 2025-07-31 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_hoteluser_options_alter_hotelvendor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_date', models.DateField()),
                ('booking_end_date', models.DateField()),
                ('booking_price', models.FloatField()),
                ('booking_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hoteluser')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hotel')),
            ],
        ),
    ]
